### ISSUE TITLE
Command for Rubik's cube experiment?

### ISSUE THREAD

**Issue by mklissa** [gpoesia/socratic-tutor#5]
Hello there,
really cool work! I was wondering if it was possible to share the command line for launching the Rubik's cube experiment? It would be appreciated :)

**Comment by gpoesia** [comment]
Hi Martin,

Thank you so much! The Rubik's Cube experiment was done by first training ConPoLe with a very large beam size first, then adapting [DeepCubeA](https://github.com/forestagostinelli/DeepCubeA)'s search implementation to use our learned policy as the A* heuristic.

To do (1), first compile the Rust environments as in the README, then launch a training job with the following config file (e.g., save it to `rubiks.json` then run `python experiment.py --experiment --config rubiks.json`):

```json
{
  "experiment_id": "rubiks-cube-expt",
  "domains": ["rubiks-cube-20"],
  "environment_backend": "Rust",
  "wandb_project": "test",
  "gpus": [0],
  "n_runs": 1,
  "agents": [
    {
      "type": "NCE",
      "name": "ConPoLe",
      "n_future_states": 1,
      "replay_buffer_size": 100000,
      "max_depth": 25,
      "beam_size": 50,
      "initial_depth": 8,
      "depth_step": 1,
      "optimize_every": 16,
      "n_gradient_steps": 256,
      "keep_optimizer": true,
      "step_every": 10000,
      "n_bootstrap_problems": 100,
      "q_function": {
        "type": "Bilinear",
        "char_emb_dim": 64,
        "hidden_dim": 256,
        "mlp": true,
        "lstm_layers": 2
      }
    }
  ],
  "eval_environment": {
    "evaluate_every": 100000,
    "eval_config": {
      "max_steps": 30,
      "n_problems": 200
    },
    "output_root": "output",
    "max_steps": 10000000,
    "print_every": 10000
  }
}
```

This should take around 2 days to fully train. The checkpoints will then be saved under `output/rubiks-cube-expt/`; with `101.pt` being the last one.

I'll retrieve our patch to DeepCubeA to then evaluate it alongside their pre-trained model and put in the repository. I could also give you our pre-trained ConPoLe model for this last part if you're interested. Just let me know!

**Comment by mklissa** [comment]
Hi Gabriel,
I really appreciate that you shared so many details to help me get started with the code, thank you! I will try it on our compute cluster and hopefully it goes smoothly. Cheers!

**Comment by gpoesia** [comment]
That sounds good! Feel free to reopen if needed.

I just remembered, one other option that might help is to add `"bootstrap_from": "RubiksGreedyHeuristic"`. This will just use a simple heuristic policy in the beginning to get the first training examples instead of the random policy, and will be discarded after it solves 100 problems (will take a few minutes at most). The random policy will eventually find enough solutions too to start learning, but will take longer.

The other option that might be helpful is adding a large beam size to eval_config, like `"beam_size": 500`. The default evaluation doesn't do any search at test time (just runs the greedy policy), but that will perform super poorly in the rubik's cube case and it will be harder to see the progress.

Let me know if I can help further!
